"""
NanoGPT Nodes for ComfyUI

Chat, video generation, and TTS nodes powered by the NanoGPT API.
"""

from .nodes.chat import NODE_CLASS_MAPPINGS as CHAT_MAPPINGS
from .nodes.chat import NODE_DISPLAY_NAME_MAPPINGS as CHAT_DISPLAY_MAPPINGS
from .nodes.simple_chat import NODE_CLASS_MAPPINGS as SIMPLE_CHAT_MAPPINGS
from .nodes.simple_chat import NODE_DISPLAY_NAME_MAPPINGS as SIMPLE_CHAT_DISPLAY_MAPPINGS
from .nodes.video_generator import NODE_CLASS_MAPPINGS as VIDEO_GENERATOR_MAPPINGS
from .nodes.video_generator import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_GENERATOR_DISPLAY_MAPPINGS
from .nodes.video_status import NODE_CLASS_MAPPINGS as VIDEO_STATUS_MAPPINGS
from .nodes.video_status import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_STATUS_DISPLAY_MAPPINGS
from .nodes.video_downloader import NODE_CLASS_MAPPINGS as VIDEO_DOWNLOADER_MAPPINGS
from .nodes.tts_generator import NODE_CLASS_MAPPINGS as TTS_GENERATOR_MAPPINGS
from .nodes.tts_status import NODE_CLASS_MAPPINGS as TTS_STATUS_MAPPINGS
from .nodes.tts_downloader import NODE_CLASS_MAPPINGS as TTS_DOWNLOADER_MAPPINGS
from .nodes.video_families import NODE_CLASS_MAPPINGS as VIDEO_FAMILIES_MAPPINGS
from .nodes.video_families import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_FAMILIES_DISPLAY_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **CHAT_MAPPINGS,
    **SIMPLE_CHAT_MAPPINGS,
    **VIDEO_GENERATOR_MAPPINGS,
    **VIDEO_STATUS_MAPPINGS,
    **VIDEO_DOWNLOADER_MAPPINGS,
    **TTS_GENERATOR_MAPPINGS,
    **TTS_STATUS_MAPPINGS,
    **TTS_DOWNLOADER_MAPPINGS,
    **VIDEO_FAMILIES_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CHAT_DISPLAY_MAPPINGS,
    **SIMPLE_CHAT_DISPLAY_MAPPINGS,
    **VIDEO_GENERATOR_DISPLAY_MAPPINGS,
    **VIDEO_STATUS_DISPLAY_MAPPINGS,
    **VIDEO_FAMILIES_DISPLAY_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
